### ISSUE TITLE
This stopped working for me in FF 29

### ISSUE THREAD

**Issue by jaygerland** [supahgreg/tab-cycler#1]
Firefox doesn't complain about it but it's no longer an option when i right-click on tabs. Can anything be done about that?

**Comment by supahgreg** [comment]
Thanks, this should be working in v3 (64d98f15d0a03efd101724975e91bd4ea7a4e80b).  The UI will be a bit different since the `splitmenu` element was removed.

I've submitted v3 to AMO, but it'll likely take a week or more to be reviewed.

**Comment by jaygerland** [comment]
Kick ass, thanks for the quick turn around. Looks good.
